upstreamConfig:
  upstreams:
    - id: backend
      path: /api/
      uri: ${CONN_BACKEND_URI}
      identityFile: ${CONN_BACKEND_IDENTITY}
      passHostHeader: false
    - id: frontend
      path: /
      uri: ${CONN_FRONTEND_URI}
      identityFile: ${CONN_FRONTEND_IDENTITY}
      passHostHeader: false
server:
  bindAddress: 0.0.0.0:${PORT}
providers:
- provider: oidc
  id: hk-id
  code_challenge_method: S256
  clientID: ${OAUTH2_PROXY_CLIENT_ID}
  clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
  scope: openid
  oidcConfig:
    issuerURL: https://hk-id.my.salesforce.com
    insecureAllowUnverifiedEmail: true
    audienceClaims:
      - aud
    emailClaim: email
    userIDClaim: preferred_username
